"""The dashboard renderer — pure, and the only writer of ``dashboard.md`` (#130).

The file has always claimed to be generated; until this module existed, nothing
generated it, so an agent retyped it on every ``progress`` invocation and
model-authored prose landed in the research record. One renderer, driven from a
:class:`~defendable_science.progress.model.Projection`, is what makes the
GENERATED banner true and ``check``'s stale-dashboard comparison enforceable.

Two properties are load-bearing:

**Idempotence.** The output is a function of the projection alone — no
timestamp, no environment, and a total sort order on rows — so two runs over an
unchanged repo are byte-identical. A date in the artifact would make every
regeneration a diff and reduce ``check``'s staleness comparison to noise.

**No rolled-up number leaves this module.** No totals, no scores, no
percentages, and no styling that reads as a red mark: ``refuted`` and ``no-go``
are successful science and render exactly like ``confirmed`` and ``publish``
(meta-spec §3.6). Gaps are *named*, never counted.

:func:`artifact_ids` is the matching reader, kept here beside the writer: the
module that decides how an id is written is the only one that can be trusted to
say which ids a dashboard claims.
"""

from __future__ import annotations

import re

from defendable_science.core.mdtable import render_table, split_cells
from defendable_science.progress.model import LEVELS, Artifact, Projection

#: The banner every generated dashboard opens with. It names the command, not
#: the skill: a reader who is told to run a skill cannot reproduce the file.
BANNER = (
    "<!-- GENERATED by `defendable-science progress dashboard` — never hand-edited. -->"
)

#: Rendered wherever a field is unset. Absence means "not yet set", never zero.
ABSENT = "—"

#: Rendered wherever a document could not be read: the state is *undetermined*,
#: which a blank cell would quietly turn into "there is nothing there".
UNKNOWN = "unknown"

#: Verdict values that record no material decision, so they are never annotated
#: as unsigned — there is nothing yet to sign.
UNDECIDED_VERDICTS: frozenset[str] = frozenset({"pending", "n/a"})

_HEADINGS: dict[str, str] = {
    "hypothesis": "Hypotheses",
    "paper": "Papers",
    "thesis": "Thesis",
}

_EMPTY: dict[str, str] = {
    "hypothesis": "_No hypothesis artifacts yet._",
    "paper": "_No paper artifacts yet._",
    "thesis": "_No thesis artifact yet._",
}

_MILESTONE_COLUMNS = ["milestone", "status", "date", "next deadline"]

_PREAMBLE = """\
# Research dashboard

A pure projection of the `status:` frontmatter each hypothesis, paper and thesis
artifact carries. Nothing here is ground truth: if this file and the frontmatter
disagree, the frontmatter wins — correct the artifact, then regenerate with
`defendable-science progress dashboard`.

Reading it: `—` means *not yet set*, never zero, and `unknown` means the
document could not be read, so its state is undetermined rather than empty. A
verdict shown as `(unsigned)` is **not yet decided** — a material decision is
real only once a named human signs it. `refuted` and `no-go` are successful
science and render exactly as `confirmed` and `publish` do. There are no totals,
no scores and no percentages here, by design."""

#: The id cell of a projected row: a backticked id inside a link. Only a real
#: ``status.id`` is written this way, so an artifact whose id is not yet set can
#: never be mistaken for one the dashboard claims exists.
_ID_CELL = re.compile(r"^\[`(?P<id>[^`]+)`\]\(")


def _columns(level: str) -> list[str]:
    """Return the table columns for `level` — hypotheses also name their paper."""
    if level == "hypothesis":
        return ["id", "paper", "verdict", "readiness", "updated"]
    return ["id", "verdict", "readiness", "updated"]


def _sort_key(artifact: Artifact) -> tuple[str, str]:
    """Return a total order over rows, so two runs are byte-identical.

    :param artifact: The row to key.
    :returns: The displayed id (or the label standing in for it) and the link,
        which disambiguates two artifacts that share an id.
    """
    return (artifact.artifact_id or artifact.label, artifact.link)


def _id_cell(artifact: Artifact) -> str:
    """Render the linked id cell, or the label when no id is set yet."""
    if artifact.artifact_id is None:
        return f"[{artifact.label}]({artifact.link}) (id not yet set)"
    return f"[`{artifact.artifact_id}`]({artifact.link})"


def _verdict_cell(artifact: Artifact) -> str:
    """Render the verdict, marking one no human has signed as undecided.

    :param artifact: The row to render.
    :returns: ``unknown`` when the document could not be read, :data:`ABSENT`
        when no verdict is recorded, the verdict itself when it is signed or
        decides nothing, and ``<verdict> (unsigned)`` otherwise — a decision
        nobody signed is not yet a decision (meta-spec §2.1).
    """
    if artifact.unreadable:
        return UNKNOWN
    if artifact.verdict is None:
        return ABSENT
    if artifact.signed_off or artifact.verdict in UNDECIDED_VERDICTS:
        return artifact.verdict
    return f"{artifact.verdict} (unsigned)"


def _plain_cell(value: str | None, *, unreadable: bool = False) -> str:
    """Render `value`, distinguishing unknown from not-yet-set."""
    if unreadable:
        return UNKNOWN
    return ABSENT if value is None else value


def _row(artifact: Artifact) -> dict[str, str]:
    """Render one artifact as a table row keyed by :func:`_columns`."""
    row = {
        "id": _id_cell(artifact),
        "verdict": _verdict_cell(artifact),
        "readiness": _plain_cell(artifact.readiness, unreadable=artifact.unreadable),
        "updated": _plain_cell(artifact.last_updated),
    }
    if artifact.level == "hypothesis":
        row["paper"] = _plain_cell(artifact.paper)
    return row


def _segments(artifact: Artifact) -> list[str]:
    """Return the detail-line segments this artifact has something to say in.

    Coverage, named blockers and unresolved understanding — everything the
    table's scannable columns cannot carry. Each is a *name*, never a count:
    ``uncovered aims: aim-3`` is actionable where "one uncovered aim" is a
    score in disguise.

    :param artifact: The row to describe.
    :returns: The segments, in reading order; empty when the artifact is clean.
    """
    segments = []
    if artifact.covers:
        segments.append(f"covers: {', '.join(artifact.covers)}")
    if artifact.uncovered_aims:
        segments.append(f"uncovered aims: {', '.join(artifact.uncovered_aims)}")
    if artifact.blocked_by:
        segments.append(f"blocked by: {'; '.join(artifact.blocked_by)}")
    if artifact.blockers:
        segments.append(f"blockers: {'; '.join(artifact.blockers)}")
    if artifact.understanding:
        segments.append(f"understanding: {'; '.join(artifact.understanding)}")
    segments.extend(artifact.notes)
    return segments


def _detail(artifact: Artifact) -> str | None:
    """Render the indented detail line, or ``None`` when there is nothing to add.

    :param artifact: The row to describe.
    :returns: The blockquote line, or ``None`` — a clean artifact is one row and
        nothing else, so the lines that *are* there are worth reading.
    """
    segments = _segments(artifact)
    if not segments:
        return None
    name = (
        artifact.label if artifact.artifact_id is None else f"`{artifact.artifact_id}`"
    )
    return f"> ↳ {name} — " + " · ".join(segments)


def _level_block(level: str, artifacts: list[Artifact]) -> str:
    """Render one level's table and the detail lines that follow it."""
    if not artifacts:
        return _EMPTY[level]
    columns = _columns(level)
    block = render_table(columns, [_row(a) for a in artifacts]).rstrip("\n")
    details = [detail for a in artifacts if (detail := _detail(a)) is not None]
    if details:
        block += "\n" + "\n".join(details)
    return block


def _milestones_block(projection: Projection) -> list[str]:
    """Render the milestones section, or nothing when the repo has no gate list.

    The gates are whatever ``thesis/milestones.yml`` holds, in the order it
    holds them: institution gates vary, the list is the author's to edit, and
    the packaged starting list is never assumed.

    :param projection: The projection being rendered.
    :returns: The section's blocks, or an empty list when there is no milestones
        file at all — a paper portfolio without a thesis is complete, not
        incomplete.
    """
    milestones = projection.milestones
    if milestones is None:
        return []
    if milestones.unknown:
        body = (
            "_The milestone list could not be read: these gates are unknown, not "
            "absent._"
        )
    elif not milestones.entries:
        body = "_No milestones recorded yet._"
    else:
        body = render_table(
            _MILESTONE_COLUMNS,
            [
                {
                    "milestone": _plain_cell(entry.name),
                    "status": _plain_cell(entry.status),
                    "date": _plain_cell(entry.date),
                    "next deadline": _plain_cell(entry.next_deadline),
                }
                for entry in milestones.entries
            ],
        ).rstrip("\n")
    return ["## Milestones", body]


def render_dashboard(projection: Projection) -> str:
    """Render the whole dashboard as markdown.

    :param projection: The collected state. The renderer adds nothing to it —
        no clock, no environment, no aggregate — which is what makes two runs
        over an unchanged repo byte-identical.
    :returns: The file's contents, newline-terminated.
    """
    blocks = [BANNER, _PREAMBLE]
    for level in LEVELS:
        rows = sorted(
            (a for a in projection.artifacts if a.level == level), key=_sort_key
        )
        blocks += [f"## {_HEADINGS[level]}", _level_block(level, rows)]
    blocks += _milestones_block(projection)
    return "\n\n".join(blocks) + "\n"


def artifact_ids(text: str) -> set[str]:
    """Return the artifact ids `text` claims, reading the format this module writes.

    The counterpart of :func:`render_dashboard`, and deliberately in the same
    module: ``check`` compares this set against the ids on disk, so a reader
    that drifted from the writer would report a repo as stale that is not.

    Only a cell holding a backticked id inside a link counts. An artifact whose
    ``status.id`` is not yet set is rendered visibly but *not* as an id, so it
    is neither silently dropped from the dashboard nor claimed to exist as an
    id nothing on disk carries.

    :param text: A dashboard's contents.
    :returns: The ids claimed, which is empty for a dashboard that claims none.
    """
    ids: set[str] = set()
    for line in text.splitlines():
        if not line.startswith("|"):
            continue
        # `split_cells` reverses the escaping `render_table` applied, so an id
        # holding a pipe survives the round trip.
        match = _ID_CELL.match(split_cells(line)[0])
        if match is not None:
            ids.add(match.group("id"))
    return ids
