#!/usr/bin/env bash
# One-shot rename sweep: honest-scholar -> defendable-science.
#
# Deleted in the final commit of the rename PR; it exists so the mechanical
# transformation is auditable in review rather than a 115-file mystery diff.
# Spec: docs/superpowers/specs/2026-07-28-defendable-science-rename-design.md
#
#   ./tools/rename-sweep.sh --dry-run   # report only, change nothing
#   ./tools/rename-sweep.sh --apply     # rewrite in place
set -euo pipefail

MODE="${1:-}"
case "$MODE" in
  --dry-run|--apply) ;;
  *) echo "usage: $0 --dry-run|--apply" >&2; exit 2 ;;
esac

cd "$(git rev-parse --show-toplevel)"

# Files that deliberately quote the old name and must survive verbatim, plus
# the lockfile (regenerated by `uv lock`, never patched). This script must
# also exclude itself: its own substitution rules below contain the search
# strings, so `git grep` would otherwise select this file too.
EXCLUDE_RE='^(honest-scholar/uv\.lock|docs/superpowers/specs/2026-07-28-defendable-science-rename-design\.md|docs/superpowers/plans/2026-07-28-defendable-science-rename\.md|tools/rename-sweep\.sh)$'

# Tracked, text (-I skips binaries), and actually containing a match.
# NOTE: git grep -E does NOT support \b (verified on this repo), so the
# selection pattern uses bare `hsch`. That is a deliberate superset -- the
# word-boundary constraint is enforced by the perl rule below, and selecting an
# extra file that contains no real match is harmless (perl rewrites nothing).
FILES=$(git grep -lIiE 'honest[-_. ]*scholar|hsch' | grep -vE "$EXCLUDE_RE" || true)

if [ -z "$FILES" ]; then
  echo "no matching files -- nothing to do"; exit 0
fi

echo "files in scope: $(printf '%s\n' "$FILES" | wc -l | tr -d ' ')"

if [ "$MODE" = "--dry-run" ]; then
  echo "--- occurrences per rule (before) ---"
  for r in 'honest-scholar-docs' 'honest--scholar\.science' 'honest-scholar\.science' \
           'honest--scholar' 'HONEST_SCHOLAR' 'HonestScholar' 'Honest Scholar' \
           'honest_scholar' 'honest-scholar'; do
    n=$(printf '%s\n' "$FILES" | tr '\n' '\0' | xargs -0 grep -ohE "$r" 2>/dev/null | wc -l | tr -d ' ')
    printf '  %-26s %s\n' "$r" "$n"
  done
  n=$(printf '%s\n' "$FILES" | tr '\n' '\0' \
      | xargs -0 perl -ne 'print "x\n" while /\bhsch\b/g' 2>/dev/null | wc -l | tr -d ' ')
  printf '  %-26s %s\n' '\bhsch\b' "$n"
  echo "(dry run -- nothing written)"
  exit 0
fi

# Order is load-bearing:
#   * the two `.science` rules must precede the bare name rules, else the
#     domain becomes defendable-science.science / defendable--science.science;
#   * honest--scholar (shields.io escaped hyphen) must precede honest-scholar.
# Rule 1 is redundant with the bare rule but is listed to make the docs-repo
# rename explicit. Perl runs in byte mode: non-ASCII passes through untouched.
printf '%s\n' "$FILES" | tr '\n' '\0' | xargs -0 perl -pi -e '
  s/honest-scholar-docs/defendable-science-docs/g;
  s/honest--scholar\.science/defendable.science/g;
  s/honest-scholar\.science/defendable.science/g;
  s/honest--scholar/defendable--science/g;
  s/HONEST_SCHOLAR/DEFENDABLE_SCIENCE/g;
  s/HonestScholar/DefendableScience/g;
  s/Honest Scholar/Defendable Science/g;
  s/honest_scholar/defendable_science/g;
  s/honest-scholar/defendable-science/g;
  s/\bhsch\b/dsci/g;
'

echo "sweep applied to $(printf '%s\n' "$FILES" | wc -l | tr -d ' ') files"
